[package]
name = "opengl-tester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glfw = "0.51.0"
image = "0.24.6"
nalgebra-glm = "0.18.0"
tobj = "3.2.5"
